### ISSUE TITLE
Recommend removing support for Python 2.7 and make minimum required version Python 3.6

### ISSUE THREAD

**Issue by JohnVillalovos** [Yubico/python-fido2#97] opened 2020-07-03 18:57 UTC
Python 2.7 had been End-of-Lifed since January 1st, 2020. https://www.python.org/doc/sunset-python-2/

I recommend dropping support for Python 2.7 and also making Python 3.6 the minimum required version.

The reason for Python 3.6 as a minimum version is that it supports type-hints and also f-strings. Both features are useful.

**Comment by sullof** [comment] 2021-01-14 01:52
It makes sense, but I am having issues with Python 3.8.
`fido2.hid.CtapHidDevice.list_devices()` is not working at all, breaking my code. 
Yubiko guys, any idea?

**Comment by dainnilsson** [comment] 2021-01-14 07:04
The plan is to drop support for Python 3 once we release 1.0. There will be at least one more release with Python 2 support prior to that.

@sullof can you provide some more details? What OS you're running, what authenticator you are trying to use, what error you're getting, and so on?

**Comment by sullof** [comment] 2021-01-18 03:07
I use fido2 to allow people to use a Yubikey with Secrez. Even if the app is in Nodejs, internally it uses a Python script to interact with Fido2 keys. The script that checks if the system is ready to work is
https://github.com/secrez/secrez/blob/master/packages/secrez/scripts/is_fido2_ready.py
It worked perfectly but recent some user contacted me to tell that it was not working anymore. In fact, I tried it with Python 3.8.6 and this is the error that I have:
```
(venv) [secrez (master)]$ python scripts/is_fido2_ready.py 
Traceback (most recent call last):
  File "scripts/is_fido2_ready.py", line 51, in <module>
    for dev in enumerate_devices():
  File "scripts/is_fido2_ready.py", line 45, in enumerate_devices
    for dev in CtapHidDevice.list_devices():
  File "/Users/sullof/venv/lib/python3.8/site-packages/fido2/hid.py", line 135, in list_devices
    for d in hidtransport.hid.Enumerate():
  File "/Users/sullof/venv/lib/python3.8/site-packages/fido2/_pyu2f/__init__.py", line 29, in Enumerate
    return InternalPlatformSwitch('Enumerate')
  File "/Users/sullof/venv/lib/python3.8/site-packages/fido2/_pyu2f/__init__.py", line 48, in InternalPlatformSwitch
    from . import macos
  File "/Users/sullof/venv/lib/python3.8/site-packages/fido2/_pyu2f/macos.py", line 152, in <module>
    iokit.IOObjectRelease.argtypes = [IO_OBJECT_T]
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python@3.8/3.8.6/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, IOObjectRelease): symbol not found
```
Thanks a lot for your help.

**Comment by sullof** [comment] 2021-01-18 03:15
I am not a Python expert. My impression is that there are many python version on my computer that cannot be uninstalled because one is used by MacOS, one is used by other tools, and so on. In the log above you can see that it calls two vrsion of python. How is it possible? Anyway, I guess that that is the cause of the problem. Any idea?

**Comment by dainnilsson** [comment] 2021-01-18 08:10
This looks like a known issue with MacOS Big Sur (https://bugs.python.org/issue41179). The real fix needs to happen in Python, but python-fido2 has a workaround for this in the meantime. You can try it out by running from the master branch of this repository instead of the released version.

**Comment by sullof** [comment] 2021-01-18 22:53
Thanks a lot. I will try and suggest that workaround to others.

**Comment by sullof** [comment] 2021-01-18 23:06
@dainnilsson 
I uninstalled fido2 and installed it from the source. However, now, the script above produces the following error:
```
$ python scripts/is_fido2_ready.py 
Traceback (most recent call last):
  File "scripts/is_fido2_ready.py", line 32, in <module>
    from fido2.extensions import HmacSecretExtension
ModuleNotFoundError: No module named 'fido2.extensions'
```
The code that fails is last line here:
```
...
from __future__ import print_function, absolute_import, unicode_literals
from fido2.hid import CtapHidDevice
from fido2.client import Fido2Client
from fido2.extensions import HmacSecretExtension
...
```

**Comment by dainnilsson** [comment] 2021-01-20 10:13
The script will need to be updated for the changes in 0.9.0, it's not backwards compatible. On that note: 0.9.0 has now been released, which includes the Big Sur fix, so you no longer need to rely on installation from git.

**Comment by dainnilsson** [comment] 2021-01-20 10:14
I'm now closing this issue as the intent to drop support for Python 2 has been made explicit in the README.

**Closed by dainnilsson** 2021-01-20 10:14 UTC
